- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: sshkey
        
- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: composer

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: artisan


- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: cert
